import { Product, Testimonial, Banner } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  // --- Smartphones (هواتف ذكية جديدة) ---
  {
    id: 'phone-16pm',
    name: 'iPhone 16 Pro Max - 512GB',
    arabicName: 'آيفون 16 برو ماكس - 512 جيجا (جديد كرت)',
    category: 'smartphones',
    brand: 'iPhone',
    price: 890000,
    originalPrice: 950000,
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&q=80&w=600',
    specs: ['شاشة Super Retina XDR مقاس 6.9 بوصة بمعدل تحديث 120 هرتز', 'معالج Apple A18 Pro تكنولوجيا 3 نانومتر المتطور من آبل', 'كاميرا فائقة الاتساع بدقة 48 ميجابكسل مع تقريب بصري 5x', 'أزرار تحكم الكاميرا اللمسية الجديدة كلياً وهيكل تيتانيوم'],
    description: 'الجيل الأحدث والأقوى من آبل بتصميم من التيتانيوم من الدرجة الخامسة، مع أسرع معالجة ذكاء اصطناعي Apple Intelligence.',
    isBestSeller: true,
    isSpecialOffer: true,
    isNewArrival: true,
    stock: 8
  },
  {
    id: 'phone-1',
    name: 'iPhone 15 Pro Max',
    arabicName: 'آيفون 15 برو ماكس - 256 جيجا',
    category: 'smartphones',
    brand: 'iPhone',
    price: 635000,
    originalPrice: 685000,
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&q=80&w=600',
    specs: ['شاشة Super Retina XDR مقاس 6.7 بوصة', 'معالج Apple A17 Pro بتكنولوجيا 3 نانومتر', 'كاميرا خلفية ثلاثية 48+12+12 ميجابكسل', 'بطارية تدوم طويلاً مع منفذ USB-C سريعة الشحن'],
    description: 'الهاتف الرائد الخارق لعام 2025 مع هيكل متين من التيتانيوم وتجربة تصوير سنمائية مذهلة بضمان المحل الحقيقي.',
    isBestSeller: true,
    isSpecialOffer: false,
    isNewArrival: false,
    stock: 12
  },
  {
    id: 'phone-2',
    name: 'Samsung Galaxy S24 Ultra',
    arabicName: 'سامسونج جالكسي S24 ألترا - 512 جيجا',
    category: 'smartphones',
    brand: 'Samsung',
    price: 660000,
    originalPrice: 720000,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&q=80&w=600',
    specs: ['شاشة Dynamic AMOLED 2X بمعدل تحديث 120 هرتز', 'معالج Snapdragon 8 Gen 3 المطور للذكاء الاصطناعي', 'كاميرا خلفية رباعية بدقة 200 ميجابكسل وقدرات زوم 100x', 'قلم S-Pen مدمج لكتابة الملاحظات والرسم السلس'],
    description: 'ثورة الذكاء الاصطناعي في جيبك. هاتف سامسونج الأقوى على الإطلاق بأداء استثنائي وتصميم تيتانيوم فاخر بضمان رسمي من محلاتنا.',
    isBestSeller: true,
    isSpecialOffer: true,
    isNewArrival: true,
    stock: 8
  },
  {
    id: 'phone-3',
    name: 'Xiaomi 14 Ultra',
    arabicName: 'شاومي 14 ألترا بالتعاون مع Leica',
    category: 'smartphones',
    brand: 'Xiaomi',
    price: 503050,
    originalPrice: 530000,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600',
    specs: ['عدسات Leica بفتحة عدسة متغيرة باستمرار', 'معالج Snapdragon 8 Gen 3 فائق الأداء', 'شاشة 120Hz AMOLED بدقة WQHD+', 'شحن سلكي سريع جداً بقدرة 90 واط'],
    description: 'كاميرا احترافية في شكل هاتف ذكي، تجربة تصوير Leica الأسطورية مع معالج رائد وتبريد مائي مغلق.',
    isBestSeller: false,
    isSpecialOffer: false,
    isNewArrival: true,
    stock: 5
  },
  {
    id: 'phone-4',
    name: 'Oppo Reno 11 Pro 5G',
    arabicName: 'أوبو رينو 11 برو الجيل الخامس - 256 جيجا',
    category: 'smartphones',
    brand: 'Oppo',
    price: 254400,
    originalPrice: 275000,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=600',
    specs: ['شاشة منحنية ثلاثية الأبعاد خرافية الألوان', 'كاميرا بورتريه بتقنيات تحسين ملامح الوجه', 'شاحن SUPERVOOC بقوة 80 واط يشحن الهاتف بعشر دقائق', 'معالج MediaTek Dimensity 8200 فائق الكفاءة'],
    description: 'خبير البورتريه الرائع بألوانه الجذابة وخلفيته المصممة كالحجر الطبيعي الفاخر للاستخدام اليومي المريح.',
    isBestSeller: false,
    isSpecialOffer: false,
    isNewArrival: false,
    stock: 14
  },
  {
    id: 'phone-5',
    name: 'Realme GT5 Pro',
    arabicName: 'ريلمي GT5 برو بطل السرعة والألعاب',
    category: 'smartphones',
    brand: 'Realme',
    price: 317470,
    originalPrice: 345000,
    image: 'https://images.unsplash.com/photo-1565849906461-0ee2ecd25827?auto=format&fit=crop&q=80&w=600',
    specs: ['معالج Snapdragon 8 Gen 3 مكسور السرعة', 'شحن مذهل بقوة 100 واط', 'نظام تبريد ثلاثي الأبعاد للحماية الحرارية للألعاب', 'شاشة OLED بدقة 1.5K فائقة السطوع'],
    description: 'قاهر الهواتف الرائدة المخصص للألعاب الثقيلة وصناع المحتوى، بأفضل قيمة وأقوى عتاد داخلي مع صيانة مضمونة لدينا.',
    isBestSeller: true,
    isSpecialOffer: true,
    isNewArrival: false,
    stock: 7
  },
  {
    id: 'phone-9',
    name: 'Tecno Camon 30 Pro 5G',
    arabicName: 'تكنو كامون 30 برو الجيل الخامس - 512 جيجا',
    category: 'smartphones',
    brand: 'Tecno',
    price: 185000,
    originalPrice: 205000,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=400',
    specs: ['كاميرا خلفية رئيسية 50 ميجابكسل بمستشعر Sony IMX890', 'شاشة AMOLED بتردد 144 هرتز وسلاسة مفرطة للعين', 'معالج MediaTek Dimensity 8200 Ultimate 5G', 'شحن لاسلكي وشحن سلكي سريع جداً بقدرة 70 واط'],
    description: 'هاتف التصوير المذهل من تكنو بأرخص سعر ومساحة تخزين ضخمة تلائم تنزيل التطبيقات وتصوير الفيديو الطويل.',
    isBestSeller: true,
    isSpecialOffer: false,
    isNewArrival: true,
    stock: 18
  },
  {
    id: 'phone-6',
    name: 'Infinix Note 40 Pro',
    arabicName: 'إنفينيكس نوت 40 برو بالشحن المغناطيسي',
    category: 'smartphones',
    brand: 'Infinix',
    price: 137800,
    originalPrice: 153000,
    image: 'https://images.unsplash.com/photo-1573148195900-7845dcb9b127?auto=format&fit=crop&q=80&w=600',
    specs: ['شاحن ذكي سريع جداً كابل ومغناطيسي', 'شاشة AMOLED منحنية بتردد 120 هرتز حماية فائقة', 'كاميرا خلفية بدقة 108 ميجابكسل مانعة للاهتزاز OIS', 'مكبرات صوت مزدوجة مضبوطة بواسطة JBL العالمية'],
    description: 'الهاتف الأقوى اقتصادياً بتصميم فخم يضاهي الهواتف الرائدة ومزود بنظام شحن مغناطيسي متطور.',
    isBestSeller: false,
    isSpecialOffer: false,
    isNewArrival: false,
    stock: 20
  },

  // --- Used & Refurbished (هواتف مستعملة نظيفة جداً كرت بضمان) ---
  {
    id: 'used-1',
    name: 'Used iPhone 13 Pro Max - 256GB Gold',
    arabicName: 'آيفون 13 برو ماكس 256 جيجا ذهبي (مستعمل نظيف جداً 95%)',
    category: 'used_devices',
    brand: 'iPhone',
    price: 365000,
    originalPrice: 395000,
    image: 'https://images.unsplash.com/photo-1621574539437-4b7cb63120b8?auto=format&fit=crop&q=80&w=400',
    specs: ['نسبة صحة البطارية 89% حقيقية أصلية', 'خالي من الخدوش والعيوب كلياً مع ملحقاته الأصلية علبة وشاحن', 'كاميرات سينمائية وتحديث شاشة 120 هرتز بطلاقة', 'ضمان تشغيل وفحص من المحل لمدة شهرين كاملين'],
    description: 'أقوى الصفقات الاقتصادية لامتلاك الآيفون العملاق. تم فحصه مخبرياً وتقنياً في ورشة الجحفلي لضمان جودته وخلوه من الصيانة السابقة.',
    isBestSeller: true,
    isSpecialOffer: true,
    isNewArrival: false,
    stock: 3
  },
  {
    id: 'used-2',
    name: 'Used Galaxy S22 Ultra 5G - Black',
    arabicName: 'سامسونج S22 ألترا 5G مستعمل أسود ملكي (نظافة كرت 98%)',
    category: 'used_devices',
    brand: 'Samsung',
    price: 295000,
    originalPrice: 320000,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&q=80&w=400',
    specs: ['سعة 256 جيجا بايت مع 12 جيجا رام أساسي', 'مرفق معه القلم الأصلي ونسبة البطارية ممتازة جداً', 'زوم تقريب كاميرات خارق 100x وشاشة جبارة واضحة', 'مكفول ومضمون تشغيل وفحص لمدة 30 يوم من المحل'],
    description: 'جهاز سامسونج الرائد بسعر خيالي ممتاز ومدروس. بديل ذكي للأجهزة الغالية وبحالة ممتازة لا تختلف عن الجديد.',
    isBestSeller: false,
    isSpecialOffer: false,
    isNewArrival: true,
    stock: 4
  },
  {
    id: 'used-3',
    name: 'Used iPhone 12 Pro - 128GB Blue',
    arabicName: 'آيفون 12 برو 128 جيجا أزرق محيطي (مستعمل نظيف 90%)',
    category: 'used_devices',
    brand: 'iPhone',
    price: 235000,
    originalPrice: 250000,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=400',
    specs: ['صحة بطارية 85% ممتازة للاستخدام اليومي', 'جسم معدني وهيكل خالي من الخدوش في الظهر', 'يدعم كافة شبكات يمن موبايل ويوه فوري الجيل الرابع', 'ضمان تبديل لمدة أسبوعين في حال وجود أي خلل مصنعي'],
    description: 'جودة آبل الرائعة وحجم مريح لليد بأفضل سعر في السوق الصنعاني.',
    isBestSeller: false,
    isSpecialOffer: true,
    isNewArrival: false,
    stock: 6
  },

  // --- Electronics (أجهزة إلكترونية ممتازة) ---
  {
    id: 'elec-1',
    name: 'Apple AirPods Max Space Gray',
    arabicName: 'سماعة رأس آبل إيربودز ماكس الأصلية',
    category: 'electronics',
    brand: 'Apple',
    price: 290000,
    originalPrice: 315000,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=600',
    specs: ['ميزة إلغاء الضوضاء النشط المتطورة ANC المعتمدة', 'الصوت المحيطي السينمائي ثلاثي الأبعاد مع تتبع الرأس', 'تصميم فاخر من الألومنيوم وجسر رأس قماشي مريح جداً', 'بطارية تدوم حتى 20 ساعة من التشغيل المتواصل'],
    description: 'أفضل سماعة رأس لعشاق الصوت النقي والتصميم العصري الفاخر. الفخامة الحقيقية مع إلغاء كامل للضجيج المحيط.',
    isBestSeller: true,
    isSpecialOffer: false,
    isNewArrival: false,
    stock: 4
  },
  {
    id: 'elec-2',
    name: 'Apple Watch Ultra 2 Titanium',
    arabicName: 'ساعة آبل الترا الجيل الثاني تيتانيوم مع سوار رياضي',
    category: 'electronics',
    brand: 'Apple',
    price: 420000,
    originalPrice: 450000,
    image: 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?auto=format&fit=crop&q=80&w=600',
    specs: ['هيكل تيتانيوم متين مقاوم للصدمات والماء حتى عمق 100 متر', 'أقوى سطوع شاشة في ساعة ذكية يصل إلى 3000 شمعة', 'عمر بطارية استثنائي يصل إلى 72 ساعة في وضع حفظ الطاقة', 'نظام تحديد المواقع GPS ثنائي التردد عالي الدقة'],
    description: 'الساعة الرياضية الأكثر صلابة لرواد المغامرات والرياضيين وعشاق التميز الرياضي والعملي.',
    isBestSeller: true,
    isSpecialOffer: true,
    isNewArrival: true,
    stock: 6
  },
  {
    id: 'elec-3',
    name: 'Anker Prime 20,000mAh Power Bank',
    arabicName: 'باور بانك أنكر برايم بقوة 200 واط شحن فائق السرعة',
    category: 'electronics',
    brand: 'Anker',
    price: 69000,
    originalPrice: 79000,
    image: 'https://images.unsplash.com/photo-1609592424085-f67f2ec6e3e5?auto=format&fit=crop&q=80&w=600',
    specs: ['سعة ضخمة 20,000 مللي أمبير تكفي لشحن الهواتف لمرات عديدة', 'شحن متزامن لـ 3 أجهزة بقدرة إجمالية شحن 200 واط', 'شاشة ملونة ذكية واضحة تعرض طاقة البطارية وحالة المنافذ', 'حجم مثالي للسفر ومتوافق مع قيود الطائرات العالمية'],
    description: 'بطارية متنقلة ذكية فائقة القوة تشحن الهواتف واللابتوبات معاً بأعلى سرعة وتحكم ذكي بالحرارة والأمان.',
    isBestSeller: true,
    isSpecialOffer: false,
    isNewArrival: false,
    stock: 15
  },
  {
    id: 'elec-4',
    name: 'MacBook Pro M3 Max 16"',
    arabicName: 'لابتوب أبل ماك بوك برو M3 ماكس - 16 بوصة شاشه ريتنا',
    category: 'electronics',
    brand: 'Apple',
    price: 1324000,
    originalPrice: 1430000,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=600',
    specs: ['معالج Apple M3 Max فائق القدرة للمهندسين والمصممين ورندرة الفيديو', 'ذاكرة موحدة 36 جيجا بايت للتصفح المتطور وعمليات معالجة الذكاء الاصطناعي', 'شاشة Liquid Retina XDR مبهرة الألوان وسلسة التحديث الاستباقي', 'بطارية عملاقة تعمل حتى 22 ساعة بشكل مستمر'],
    description: 'وحش الانتاجية والتصميم بلا منازع لعشاق الأداء المطلق وسرعة الرندر ومعالجة الفيديوهات الـ 8K في اليمن.',
    isBestSeller: false,
    isSpecialOffer: true,
    isNewArrival: true,
    stock: 2
  },

  // --- Accessories (إكسسوارات الهواتف الأصلية) ---
  {
    id: 'acc-1',
    name: 'iPhone 15 Pro Max Silicon Case - MagSafe',
    arabicName: 'كفر آيفون 15 برو ماكس السليكون الأصلي مع المغناطيس MagSafe',
    category: 'accessories',
    brand: 'iPhone',
    price: 26000,
    originalPrice: 31000,
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&q=80&w=600',
    specs: ['يدعم الشحن المغناطيسي السريع MagSafe وبقوة تثبيت هائلة', 'حماية متكاملة من الصدمات والخدوش بحواف مرتفعة حامية للشاشة', 'ملمس سيليكوني حريري خارجي ناعم وبطانة ميكروفايبر داخلية', 'متوفر بألوان فاخرة متعددة تناسب الهاتف وتمنع الاصفرار كلياً'],
    description: 'حماية أنيقة ومثالية لهاتفك الآيفون ليدوم معك بأعلى درجات الأمان ودون تغبيش أو اصفار للجراب.',
    isBestSeller: true,
    isSpecialOffer: false,
    isNewArrival: false,
    stock: 35
  },
  {
    id: 'acc-2',
    name: 'Anker Nano USB-C Fast Charger 30W',
    arabicName: 'شاحن أنكر نانو فائق السرعة 30 واط مخرج تايب سي',
    category: 'accessories',
    brand: 'Anker',
    price: 13200,
    originalPrice: 18500,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=600',
    specs: ['قوة شحن سريعة 30 واط تناسب شحن الآيفون والسامسونج والآيباد بشكل مريح', 'حجم نانو فائق الصغر يسهل حمله ويوفر مساحة في المقبس والسيارة', 'تقنية مراقبة حرارية ذكية لمنع ارتفاع حرارة الأجهزة المتصلة', 'أكثر كفاءة وأمانا بفضل تقنية GaN الحديثة بديلة السيليكون'],
    description: 'الشاحن الأفضل والأكثر أماناً وبحجم عقلة الإصبع يشحن هاتفك لـ 50% بخمس وعشرين دقيقة فقط.',
    isBestSeller: true,
    isSpecialOffer: true,
    isNewArrival: true,
    stock: 50
  },
  {
    id: 'acc-3',
    name: 'MagSafe Car Phone Mount Active',
    arabicName: 'حامل هاتف السيارة المغناطيسي ماج سيف للتابلوه وفتحة المكيف',
    category: 'accessories',
    brand: 'Baseus',
    price: 15900,
    originalPrice: 21000,
    image: 'https://images.unsplash.com/photo-1584438784894-089d6a128f3e?auto=format&fit=crop&q=80&w=600',
    specs: ['مغناطيس نيوديميوم فائق القوة يثبت الهاتف في أصعب مطبات الطرق الوعرة باليمن', 'قابل للدوران 360 درجة لزوايا رؤية مثالية أثناء القيادة', 'آمن تماماً على لوحة السيارة ومكثفات تبريد المكيف ولا يسبب الخدوش', 'متوافق مع جميع الهواتف التي تدعم الماج سيف ولجميع الحوامل'],
    description: 'تمتع بقيادة آمنة وهاتفك مثبت بأقوى نظام مغناطيسي لمشاهدة الملاحة GPS بوضوح كامل وسلاسة.',
    isBestSeller: false,
    isSpecialOffer: false,
    isNewArrival: false,
    stock: 25
  },

  // --- Recharge Cards (كروت باقات وبطاقات شحن - خدمات فروع فوري) ---
  {
    id: 'card-1',
    name: 'Yemen Mobile 4G Package Credit 5000',
    arabicName: 'تعبئة رصيد يمن موبايل فوري فئة 5000 ريال (شحن رصيد وباقات)',
    category: 'recharge_cards',
    brand: 'Yemen Mobile',
    price: 5000,
    originalPrice: 5100,
    image: 'https://images.unsplash.com/photo-1565849906461-0ee2ecd25827?auto=format&fit=crop&q=80&w=400',
    specs: ['شحن فوري ومباشر إلى رقم الجوال في أقل من 5 دقائق', 'صالحة لتنشيط باقات الـ 4G الفائقة والإنترنت والاتصال', 'تتم المعالجة مباشرة بواسطة قسم الحسابات عبر الواتساب', 'خدمة آمنة ودقيقة لتوفير مشقة البحث عن فروع الشحن'],
    description: 'اشحن رصيدك في يمن موبايل وأنت في منزلك بكل راحة بدفع فوري عبر الكريمي أو النجم ومتابعة عبر الواتساب.',
    isBestSeller: true,
    isSpecialOffer: false,
    isNewArrival: true,
    stock: 500
  },
  {
    id: 'card-2',
    name: 'SabaFon 100 Unit Card Recharge',
    arabicName: 'تعبئة رصيد سبأفون فئة 100 وحدة فوري للرقم مباشر مع الضريبة',
    category: 'recharge_cards',
    brand: 'SabaFon',
    price: 1200,
    originalPrice: 1200,
    image: 'https://images.unsplash.com/photo-1609592424085-f67f2ec6e3e5?auto=format&fit=crop&q=80&w=400',
    specs: ['شحن مباشر برقم الهاتف فوري لشبكة سبأفون الشمال', 'تحصل على كامل الوحدات مع احتساب الضريبة الحكومية مسبقاً', 'يتيح تفعيل باقات الاتصال السريعة وباقات الرسائل', 'تواصل فوري مع الدعم عبر الواتساب لتأكيد رقم الهاتف الشاحن'],
    description: 'شحن رصيد سبأفون بسرعة وسلاسة تامة. أمن وأسرع معاملات تعبئة الأرصدة في صنعاء.',
    isBestSeller: false,
    isSpecialOffer: false,
    isNewArrival: false,
    stock: 999
  },
  {
    id: 'card-3',
    name: 'YOU Telecom 4G Clever Bundle 3000',
    arabicName: 'تفعيل باقة يو كليفر الأسبوعية أو الشهرية للمشتركين فوري',
    category: 'recharge_cards',
    brand: 'YOU',
    price: 3300,
    originalPrice: 3400,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=400',
    specs: ['تفعيل فوري لجميع خطوط الدفع المسبق لشبكة YOU', 'تتضمن الباقة حزم إنترنت متميزة ودقائق اتصال مجانية شبكية', 'تصلك رسالة التأكيد من الشركة فوراً بمستند العملية الصادر', 'إمكانية طلب الشحن لأي صديق أو فرد عائلي برقم جواله'],
    description: 'تنشيط سريع ومباشر لباقات YOU الأسبوعية والشهرية الأكثر طلباً في صنعاء والجمهورية متاح للطلب المتواصل.',
    isBestSeller: true,
    isSpecialOffer: true,
    isNewArrival: true,
    stock: 600
  },
  {
    id: 'phone-fold6',
    name: 'Samsung Galaxy Z Fold 6',
    arabicName: 'سامسونج جالكسي زد فولد 6 (جديد كرت 512G)',
    category: 'smartphones',
    brand: 'Samsung',
    price: 945000,
    originalPrice: 990000,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=400',
    specs: ['شاشة رئيسية مرنة قابلة للطي Dynamic AMOLED 2X', 'معالج Snapdragon 8 Gen 3 الرائد المطور للذكاء الاصطناعي', 'ذاكرة عشوائية 12 جيجابايت لتجربة تسوق وتناقل خرافية السلاسة', 'تصميم نحيف فائق المتانة مفصلة ألمنيوم مدرعة Armour Aluminum'],
    description: 'الهاتف الأرقى والأكثر فخامة لرجال الأعمال وهواة التقنيات الحديثة، يقدم مزيج لابتوب وجوال في آنٍ معاً بضمان الجحفلي المتكامل.',
    isBestSeller: true,
    isSpecialOffer: false,
    isNewArrival: true,
    stock: 2
  },
  {
    id: 'used-4',
    name: 'Used Galaxy S21 Ultra 5G',
    arabicName: 'سامسونج جالكسي S21 ألترا 5G مستعمل (نظيف جداً كرت 90%)',
    category: 'used_devices',
    brand: 'Samsung',
    price: 185000,
    originalPrice: 205000,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&q=80&w=400',
    specs: ['سعة تخزين ضخمة 256 جيجابايت مع كاميرات خرافية الزوم 100x', 'يدعم شبكات 5G و 4G يمن موبايل بقوة وثبات تام', 'بطارية ممتازة تدوم يوماً كاملاً في العمل المستمر', 'مفحوص ومثبت خلوه من أي مشاكل مصنعية بضمان فحص شهر من المحل'],
    description: 'الأداء الفخم والتصوير السينمائي الأسطوري بسعر مذهل في متناول يدك بالريال اليمني وبضمان محل حقيقي.',
    isBestSeller: false,
    isSpecialOffer: true,
    isNewArrival: false,
    stock: 5
  },
  {
    id: 'card-4',
    name: 'Yemen Mobile super 10000 YER Pack',
    arabicName: 'شحن باقة يمن موبايل سوبر فوري فئة 10,000 ريال يمني',
    category: 'recharge_cards',
    brand: 'Yemen Mobile',
    price: 10000,
    originalPrice: 10100,
    image: 'https://images.unsplash.com/photo-1565849906461-0ee2ecd25827?auto=format&fit=crop&q=80&w=410',
    specs: ['شحن مباشر برقم الهاتف فوري لشبكة يمن موبايل', 'تحتوي على باقة سوبر 4G الشهرية مكالمات ورصيد إنترنت جبار', 'يتيح تفعيل الإنترنت الأسرع في اليمن 4G LTE مباشرة', 'يتم التحقق الفوري بواسطة المهندس المشرف في متجرنا'],
    description: 'الباقة الأكثر كفاءة وطلباً لمستخدمي الهواتف الذكية وتصفح يوتيوب بسعة وسرعة عالية وبثبات في صنعاء والجمهورية.',
    isBestSeller: true,
    isSpecialOffer: false,
    isNewArrival: true,
    stock: 350
  }
];

export const INITIAL_BANNERS: Banner[] = [
  {
    id: 'banner-1',
    title: 'عصر جديد من القوة مع آيفون 16 برو ماكس التيتانيوم الأقوى',
    subtitle: 'متوفر الآن بالريال اليمني وبضمان وكالة حقيقي مع ملصق حماية مجاني في صنعاء',
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&q=80&w=1200',
    linkText: 'تسوق الآن بالريال اليمني',
    colorTheme: 'from-amber-955 via-slate-950 to-amber-600/30',
    productId: 'phone-16pm'
  },
  {
    id: 'banner-2',
    title: 'قسم الأجهزة المستعملة النظيفة "كرت" لخير الصفقات الاقتصادية',
    subtitle: 'آيفونات وسامسونج مستوردة من أمريكا، خاضعة لـ 32 بند فحص وضمانة المحل',
    image: 'https://images.unsplash.com/photo-1621574539437-4b7cb63120b8?auto=format&fit=crop&q=80&w=1200',
    linkText: 'استكشف عروض المستعمل',
    colorTheme: 'from-slate-950 via-gray-950 to-yellow-600/30',
    productId: 'used-1'
  },
  {
    id: 'banner-3',
    title: 'ثورة الذكاء الاصطناعي مع Samsung Galaxy S24 Ultra',
    subtitle: 'متوفر الآن بأفضل سعر صرف محلي وتحت رعاية الأستاذ جمال الجحفلي دارس الخط العام',
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&q=80&w=1200',
    linkText: 'اطلب مواصفات سامسونج',
    colorTheme: 'from-blue-950 via-slate-950 to-indigo-950/30',
    productId: 'phone-2'
  }
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  {
    id: 't-1',
    name: 'المهندس أحمد اليماني',
    rating: 5,
    comment: 'محل الجحفلي هو الأفضل بلا منازع في صنعاء! تعامل راقي وأمانة لا حدود لها. اشتريت سامسونج S24 Ultra ومعه ضمان الوكالة بالريال اليمني وبسعر ممتاز تحت إشراف الأستاذ جمال الجحفلي شخصياً.',
    date: '2026-05-10'
  },
  {
    id: 't-2',
    name: 'الدكتور عصام الدارسي',
    rating: 5,
    comment: 'إكسسواراتهم أصلية 100% ومتنوعة جداً. خدمة الشحن الفوري للبطاقات وتنشيط رصيد وباقات يمن موبايل في ثوانٍ، وموقع المحل على الخط العام في دارس يسهل الوصول إليه كثيراً.',
    date: '2026-05-18'
  },
  {
    id: 't-3',
    name: 'أمل الخالدي',
    rating: 4,
    comment: 'سرعة استجابة مذهلة على الواتساب وخدمة توصيل سريعة لداخل صنعاء. الهواتف المستعملة نظيفة جداً وكأنها جديدة وبأسعار ممتازة جداً بالعملة المحلية.',
    date: '2026-05-20'
  }
];

export const SHOP_INFO = {
  name: 'محلات الجحفلي للهواتف الذكية ومستلزماتها',
  owner: 'جمال الجحفلي',
  location: 'اليمن – صنعاء – دارس – الخط العام',
  phone: '781831833',
  whatsapp: '967781831833', // Fully qualified international number for link generation
  hours: 'يومياً: 9:00 صباحاً – 11:00 مساءً (الجمعة من 3:00 عصراً حتى 11:00 مساءً)',
  description: 'مزيج الأمان والضمان الرائد بأيدي يمنية منذ أكثر من عشر سنوات؛ نقدم لكم الأجهزة الذكية وملحقاتها الأصلية وشحن فوري للبطاقات بأسعار لا تقبل المنافسة مع أرقى مستويات خدمة ما بعد البيع في العاصمة صنعاء.'
};

export const EXCHANGE_RATES = {
  updatedAt: 'تحديث اليوم (صنعاء)',
  saudiRiyal: 140, // Rial buy
  saudiRiyalSell: 141,
  usDollar: 530,
  usDollarSell: 535,
  note: 'الأسعار تقريبية وتعتمد على حالة السوق اليومية لبيع وشراء العملات في صنعاء.'
};
